var json_data_serie = {
  data_serie: {
    serie: 'Rick y Morty',
    tipo: "Temporada",
    logot: 'art.png',
    exter: 'https://www.youtube.com/channel/UC9sSBrqen7t5G7MsCGTe5zA?sub_confirmation=1',
    prima: 'rgb(899, 197, 102)',
    ath: 'Pepinillo Rick'
  },
  caps: [
    {url: "https://drive.google.com/file/d/1WHDLkJahKI2N_kiOfc4zcC5t7-P3x2Lg/preview", tem: 1, epi: 1, tit: "2 Buscando las semillas"},
    {url: "https://drive.google.com/file/d/1dFagYRX2655OKARHQFOBwGC9aGvvOfne/preview", tem: 1, epi: 2, tit: "Invasión canina"},
    {url: "https://drive.google.com/file/d/1V5ieY09eTwgM57zbxOPNbWPVJUg5xKcB/preview", tem: 1, epi: 3, tit: "Parque Anatómico"},
    {url: "https://drive.google.com/file/d/1SNMrOrQxzpcwSBasGXj9ahSs76JCpH7u/preview", tem: 1, epi: 4, tit: "La simulación alienígena"},
    {url: "https://drive.google.com/file/d/12uvJuWLSymmqnx6DXYD3oblQt4ZmOhgn/preview", tem: 1, epi: 5, tit: "Meeseeks destructores"},
    {url: "https://drive.google.com/file/d/1Re962VzZQx1wsV9G-NaA7qldx2-707Jz/preview", tem: 1, epi: 6, tit: "La poción de Rick"},
    {url: "https://drive.google.com/file/d/1EkWZvIzioD_7VDW5et7T_wSHUrYmQBpf/preview", tem: 1, epi: 7, tit: "Criando un Gazorpazorp"},
    {url: "https://drive.google.com/file/d/1MBRO6jyLZQaU4Sxd7uO0TZytj-Sc49HR/preview", tem: 1, epi: 8, tit: "Televisión Interdimensional"},
    {url: "https://drive.google.com/file/d/14PUWgAe8sSXAQb51sbAZ1eJEyAGfAEr7/preview", tem: 1, epi: 9, tit: "Cosas necesarias"},
    {url: "https://drive.google.com/file/d/1wnPnlTr4oiruAeiy23F9pWa90TlEWslr/preview", tem: 1, epi: 10, tit: "Encuentros cercanos a lo Rick"},
    {url: "https://drive.google.com/file/d/1h8QZH23-enAIMvPQmQUhDx0RggInQeUM/preview", tem: 1, epi: 11, tit: "Es hora de la fiesta"},
    {url: "https://drive.google.com/file/d/17K6w7jmRqRI_mr5E7Wl24d6h5GniNjqY/preview", tem: 2, epi: 1, tit: "Rupturas en el tiempo"},
    {url: "https://drive.google.com/file/d/1Wvj-P9nEHGUg0wls1T6ELpj6AKlaLKtj/preview", tem: 2, epi: 2, tit: "Morty escapa en la noche"},
    {url: "https://drive.google.com/file/d/1PtZ9L08MHi_rh5FveK4_okAfRjZPAQr-/preview", tem: 2, epi: 3, tit: "Asimilación autoerótica"},
    {url: "https://drive.google.com/file/d/1Jv6HSFF3sBP23iIPLoPsMi9Hky-dqTZk/preview", tem: 2, epi: 4, tit: "Rick vengador del futuro"},
    {url: "https://drive.google.com/file/d/1kP6jVRg0aIXsLBQUh3Om8hQ77p5ToiTq/preview", tem: 2, epi: 5, tit: "Ponte Rickoso"},
    {url: "https://drive.google.com/file/d/1JrCeYe2N2qF2jQmQ40ELea-J6xZIMzKt/preview", tem: 2, epi: 6, tit: "Los Ricks deben estar locos"},
    {url: "https://drive.google.com/file/d/1YQkPDVRu4LyADi40wIxqzDecwfEnhmN6/preview", tem: 2, epi: 7, tit: "Problemas con Mini Rick"},
    {url: "https://drive.google.com/file/d/1l_2wf6JqGsOO113ga744d2D88n-04O1s/preview", tem: 2, epi: 8, tit: "Televisión Interdimensional 2"},
    {url: "https://drive.google.com/file/d/1ILee8iCEcQyFVHToQoUeLDSSQU9nUpzY/preview", tem: 2, epi: 9, tit: "El día de la purga"},
    {url: "https://drive.google.com/file/d/1sxC_XjHuvrD0NL_b0x2rmSjrPi9PRSlC/preview", tem: 2, epi: 10, tit: "La Squanch boda"},
    {url: "https://drive.google.com/file/d/1hJKvREyCQsXRtNiR2naz7t5haJmbQixT/preview", tem: 3, epi: 1, tit: "La redención de Rick"},
    {url: "https://drive.google.com/file/d/17LM_dXQq8R7gokU0muaJgyyFSpzUPCgP/preview", tem: 3, epi: 2, tit: "Rickusando la piedra"},
    {url: "https://drive.google.com/file/d/1iEWZhwwrUxiWyhHfCkVdjJ_TCSZkZAgv/preview", tem: 3, epi: 3, tit: "Pepinillo Rick"},
    {url: "https://drive.google.com/file/d/18ds2LQocPp2Z8MP6kVb6u46Gu2_54reD/preview", tem: 3, epi: 4, tit: "Los Vindicadores"},
    {url: "https://drive.google.com/file/d/1WPVLnoDhJH1O_ByHfHCAtPQ1ljsJtTDK/preview", tem: 3, epi: 5, tit: "La conspiración Whirly Dirly"},
    {url: "https://drive.google.com/file/d/1HYf2a6TkBJ_wcxXXR7pEKUkVIEOWzelZ/preview", tem: 3, epi: 6, tit: "Descanso y Ricklajación"},
    {url: "https://drive.google.com/file/d/1rUwfZu_ma2xA2eBW0uOl7bHUeNPkbmBF/preview", tem: 3, epi: 7, tit: "Cuentos de la Ciudadela"},
    {url: "https://drive.google.com/file/d/1n84TkzwfjBS2gTDHa333-QwBegME3mZI/preview", tem: 3, epi: 8, tit: "Los recuerdos de Morty"},
    {url: "https://drive.google.com/file/d/1nre8BKN_W5VmYK77bYE5CWgTHq5nuxiL/preview", tem: 3, epi: 9, tit: "ABC de Beth"},
    {url: "https://drive.google.com/file/d/144KgNpvmn8uwCsGMdSe3wPJT8INKSPoI/preview", tem: 3, epi: 10, tit: "Día de Rick y Morty"},
    {url: "https://drive.google.com/file/d/1Ge1b0th3gqXZLzPCJ70anj7_lnX2D2u8/preview", tem: 4, epi: 1, tit: "Aprovechando el Mortymento"},
    {url: "https://drive.google.com/file/d/1DTDtiqw4Ch8XVnxEx1J2dASGpuh0a8m0/preview", tem: 4, epi: 2, tit: "El Anciano y el trono"},
    {url: "https://drive.google.com/file/d/1vPi77K3zTvekP6DCXzmtMss3iLc4P9MC/preview", tem: 4, epi: 3, tit: "Una Pandilla para el Patético Morty"},
    {url: "https://drive.google.com/file/d/1l65fxuLq7CrsFVj9et0BxCQTX0xwFuYS/preview", tem: 4, epi: 4, tit: "La Ley y el Dragorden"},
    {url: "https://drive.google.com/file/d/1eDzTdDoPPvqPHpSylc6hMk8ZarWSPmsc/preview", tem: 4, epi: 5, tit: "Rattlestar Rickláctica"},
    {url: "https://drive.google.com/file/d/1auccYCsG9rJF_UlGwXkJYgeJtSNyjWCu/preview", tem: 4, epi: 6, tit: "Un tren de antologías"},
    {url: "https://drive.google.com/file/d/1TMlMVA4ag2ijeTFCurklVXIPeV0J08cn/preview", tem: 4, epi: 7, tit: "Alienígenas"},
    {url: "https://drive.google.com/file/d/1taYJrBn-xNST7oeRFH8GFwxRffBIufQw/preview", tem: 4, epi: 8, tit: "El Episodio del Tanque de Ácido"},
    {url: "https://drive.google.com/file/d/1ii_daCktYfCXPNhoRj0PrH48MRGcrXjy/preview", tem: 4, epi: 9, tit: "Childrick of Morta"},
    {url: "https://drive.google.com/file/d/1htD6lh-XcfEIZT9GW3ODo8ohaEt0wWEQ/preview", tem: 4, epi: 10, tit: "El Rickgreso del Jerri"},
    {url: "https://drive.google.com/file/d/1NAZGse6MFzihZTFr1djoqomqVROLvVX3/preview", tem: 5, epi: 1, tit: "Mi Cena con André a la Morty"},
    {url: "https://drive.google.com/file/d/1rQP1CH1RJLa9bX7T7tU8_ZDfK6bjjrY6/preview", tem: 5, epi: 2, tit: "Mortyplicidad"},
    {url: "https://drive.google.com/file/d/18gu0Qk__a4P7cBJBBJldkup5b0ATY_9_/preview", tem: 5, epi: 3, tit: "Una Mortyandad conveniente"},
    {url: "https://drive.google.com/file/d/1YhpOeH35SebRVyjz5MX8bXXE-5mC_i6o/preview", tem: 5, epi: 4, tit: "Día de la Rickdependencia"},
    {url: "https://drive.google.com/file/d/10MrKBEO3Pb7J9tehv3zb1v8YfCIDuyid/preview", tem: 5, epi: 5, tit: "Grickfitti Amortycano"},
    {url: "https://drive.google.com/file/d/14qQTy3Wv_lPzftHHVjmCqX6HpDxnUhQQ/preview", tem: 5, epi: 6, tit: "El increíble día de explota Acción de Gracias"},
    {url: "https://drive.google.com/file/d/1YwJbJpwRmVa-AwnKgCeS7ZhWFKcylDmB/preview", tem: 5, epi: 7, tit: "Gotron, Jerrys y Rickvangelion"},
    {url: "https://drive.google.com/file/d/1BxMw_2BtRCoY2qLRASTU1HThYgfWbUg2/preview", tem: 5, epi: 8, tit: "Eterna amistad de una mente sin Rickcuerdos"},
    {url: "https://drive.google.com/file/d/18ojx7lr_mkOrwRja0jCp7cPbMGoXJ-xk/preview", tem: 5, epi: 9, tit: "Cómo Sobrevivir a Mi Rick"},
    {url: "https://drive.google.com/file/d/1JpQ86E1l78EvGsS5Co200KJvmfz5OvcW/preview", tem: 5, epi: 10, tit: "Rickmurai Jack"},
    {url: "https://drive.google.com/file/d/1aZdxWl83omWujba6C6j7lI47B616A1QZ/preview", tem: 6, epi: 1, tit: "Solaricks"},
    {url: "https://drive.google.com/file/d/1Clnu0TcNLhgxMk6w0ilQBKUCfJUdUSHX/preview", tem: 6, epi: 2, tit: "Rick, una Morty vida"},
    {url: "https://drive.google.com/file/d/1PvHIRe4BdvkyLN79B54tDQeaDoc3GCrb/preview", tem: 6, epi: 3, tit: "Gemelinstinto Béthico"},
    {url: "https://drive.google.com/file/d/1plsgGijZgml4t0sG1yHFrTbJbSZypDc1/preview", tem: 6, epi: 4, tit: "Familia nocturna"},
    {url: "https://drive.google.com/file/d/1HLAqQ_E_Ydpf7yuRfc-WCD1A9y4hsj6P/preview", tem: 6, epi: 5, tit: "DeSmithno final"},
    {url: "https://drive.google.com/file/d/1PRU_fNehr_VwvxaS7EAwu1XmXGfKDdFe/preview", tem: 6, epi: 6, tit: "Mundo JuRicksico"},
    {url: "https://drive.google.com/file/d/1YkIK_cS-JUtsb73Xe4o4mIcuhmLbPAc7/preview", tem: 6, epi: 7, tit: "La meta naRicktiva"},
    {url: "https://drive.google.com/file/d/1fqDaibheZys8y_kTUA4evoN6LFObN5gh/preview", tem: 6, epi: 8, tit: "Anal-ízame"},
    {url: "https://drive.google.com/file/d/1RrmSCcu6nP6ogKRQlGynuZKnbefwMKMu/preview", tem: 6, epi: 9, tit: "El sacrificio del rey Morturo"},
    {url: "https://drive.google.com/file/d/1Jp0W8BUhDC1b3fKrNsRSEXQ7jvn10f1A/preview", tem: 6, epi: 10, tit: "Rickacciones de Mortyvidad"}
  ]
}